# Generated by Django 5.2.7 on 2025-10-24 01:57

import book_app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Dystopian', 'Dystopian'), ('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('LGBTQ', 'Lgbtq'), ('Historical Fiction', 'Historical Fiction'), ('Young Adult', 'Young Adult'), ("Children's Fiction", 'Child Fiction'), ('Autobiography', 'Autobiography'), ('Biography', 'Biography'), ('Self-Help', 'Self Help'), ('History', 'History'), ('Hobbies and Crafts', 'Hobbies'), ('True Crime', 'True Crime')], max_length=100)),
                ('date_started', models.DateField(default=datetime.date.today)),
                ('date_ended', models.DateField()),
                ('notes', models.TextField()),
                ('rating', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Reading', 'Reading'), ('Did Not Finish', 'Did Not Finish'), ('Done', 'Finished')], max_length=50)),
                ('media_type', models.CharField(choices=[('E', 'Ebook'), ('A', 'Audiobook'), ('P', 'Physical Copy')], max_length=50)),
                ('cover_photo', models.ImageField(upload_to=book_app.models.cover_upload_path)),
            ],
        ),
    ]
