# Generated by Django 5.2.7 on 2025-10-24 03:32

import book_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to=book_app.models.cover_upload_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
