# Generated by Django 5.2.7 on 2025-10-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_alter_book_cover_photo_alter_book_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_ended',
            field=models.DateField(blank=True),
        ),
    ]
