# Generated by Django 5.2.7 on 2025-10-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
